-- ----------------------------
-- Table structure for ERP_APPLIANCE
-- ----------------------------
DROP TABLE IF EXISTS `ERP_APPLIANCE`;
CREATE TABLE `ERP_APPLIANCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `STORE_ID` bigint(20) DEFAULT NULL COMMENT '店铺ID',
  `CREATED_BY` bigint(20) DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `NAME` varchar(50) DEFAULT NULL COMMENT '器械名称',
  `SEARCH_NAME` varchar(50) DEFAULT NULL COMMENT '器械名称拼音首字母字符串',
  `DEPARTMENT_TYPE_CODE` INT DEFAULT 0 COMMENT '科室类别 （一级分类）',
  `PACKAGE_TYPE_CODE` INT DEFAULT 0,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for ERP_DEPARTMENT_TYPE
-- ----------------------------
DROP TABLE IF EXISTS `ERP_DEPARTMENT_TYPE`;
CREATE TABLE `ERP_DEPARTMENT_TYPE` (
  `CODE` INT DEFAULT 0,
  `NAME` varchar(50) DEFAULT NULL COMMENT '器械名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ERP_DEPARTMENT_TYPE
-- ----------------------------
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('1', '4F_CICU');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('2', '4F手术室-心脏');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('3', '2F人流室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('4', '外来器械');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('5', '3F盆底康复科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('6', '4F手术室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('7', '8F西心血管');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('8', '日间手术室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('9', '5F_NICU');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('10', '4F胃镜');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('11', '5F_PICU');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('12', '低温腔镜（妇科手术室）');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('13', '4F手术室-儿科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('14', '5F新生儿');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('15', '6F西产前');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('16', '5F西-外科NICU');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('17', '低温腔镜（儿科手术室）');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('18', '4F口腔科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('19', '2F眼科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('20', '11F东产八');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('21', '4F产前诊断中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('22', '10F东神经内科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('23', '10F东内分泌');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('24', '14F层流病房东区');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('25', '14F血液科西区');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('26', '4F耳鼻喉');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('27', '8F东五官科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('28', '3F妇科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('29', '通用包');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('30', '母乳库');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('31', '1F儿科观察室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('32', '6F东产房');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('33', '营养室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('34', '4F生殖中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('35', '13F脐血库');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('36', '12东产后六组');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('37', '3F检验科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('38', '7F东产后3组');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('39', '4F手术室-妇科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('40', '5F血液日间病房');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('41', '1F介入治疗室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('42', '低温器械（心脏手术室）');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('43', '骨科专科（珠）');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('44', '13F冻存室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('45', '1F妇产科急诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('46', '3F成人综合门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('47', '9F西普外科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('48', '11F西生殖妇科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('49', '1F配置中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('50', '12F西妇科肿瘤');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('51', '7F西产后2组');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('53', '3F儿外科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('54', '3F东出生队列研究所');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('55', '9F东骨泌尿外科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('56', '1F放射科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('57', '早产防治实验室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('58', '13F精密仪器');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('59', '10F呼吸消化');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('60', '儿内科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('61', '2F呼吸门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('62', '整形美容外科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('63', '3F儿内(B超室)');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('64', '2F消化科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('65', '3F成人内科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('66', '1F儿童补液室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('67', '隔离门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('68', '2F特诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('69', '1F影像中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('70', '儿科B超室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('71', '小儿复苏室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('72', '2F儿科特诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('73', '3F儿内');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('74', '2F皮肤科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('75', '3F产科门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('76', '3F乳腺外科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('77', '3F成人中医');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('78', '3F产科抽血室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('79', '13F细胞遗传');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('80', '1F体检中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('81', '2F妇科抽血室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('82', '3F中医妇科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('83', '5F免疫日间病区');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('84', '日间手术病房');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('85', '13F内分泌实验室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('86', '13F外科实验室(1308室)');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('87', '13F血液实验中心');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('88', '13F免疫学实验室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('89', '3F微创消化功能室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('90', '低温器械（人流室)');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('91', '3F儿童早期综合发展');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('92', '中医儿科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('93', '3F内分泌门诊');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('94', '妇科日间手术病区（珠）');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('95', '4F产前诊断中心实验室');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('96', '低温－骨科专用');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('97', '低温灭菌包');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('98', '教育管理科');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('99', '科教科(保利509)');
INSERT INTO `ERP_DEPARTMENT_TYPE` VALUES ('100', '儿保科');
-- ----------------------------
-- Table structure for ERP_PACKAGE_TYPE
-- ----------------------------
DROP TABLE IF EXISTS `ERP_PACKAGE_TYPE`;
CREATE TABLE `ERP_PACKAGE_TYPE` (
  `CODE` INT DEFAULT 0,
  `NAME` varchar(50) DEFAULT NULL COMMENT '器械名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ERP_PACKAGE_TYPE
-- ----------------------------
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('1', '纸塑包');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('2', '无纺布(单层)');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('3', '无纺布(双层)');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('4', '无纺布(三层)');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('5', '清洗消毒包装');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('6', '铁质容器');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('7', '棉布包');
INSERT INTO `ERP_PACKAGE_TYPE` VALUES ('8', '硬式灭菌专用器');