-- ----------------------------
-- Jelynn 2018/3/14 添加
-- ----------------------------
ALTER TABLE `ROBOT_MAPZIP_XREF` DROP COLUMN `LAST_MAP_ZIP_ID`;
ALTER TABLE `ROBOT_MAPZIP_XREF` DROP COLUMN `NEW_MAP_ZIP_ID`;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `MAP_ZIP_ID`  bigint(20) DEFAULT NULL COMMENT '地图压缩包ID' ;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `SCENE_ID`  bigint(20) DEFAULT NULL COMMENT '场景ID';
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `UPDATE_TIME`  datetime DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `DELETE_FLAG`  INT DEFAULT NULL COMMENT '删除标志位 0 :正常 1：删除' ;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `DELETE_TIME`  datetime DEFAULT NULL COMMENT '删除时间';

-- 修改手术室下单系统中的名称的长度
ALTER TABLE `ERP_APPLIANCE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_APPLIANCE_DEPARTMENT_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_APPLIANCE_PACKAGE_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_OPERATION_DEPARTMENT_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_OPERATION_TYPE` modify  NAME VARCHAR(200) ;

-- ----------------------------
-- Jelynn 2018/3/15 添加  修改电梯消息的表名，
-- ----------------------------
ALTER TABLE `AS_ELEVATOR_NOTICE` ADD COLUMN `TYPE`  int DEFAULT 0 COMMENT '消息类型 1:电梯pad消息  2:多站融合消息' ;
ALTER TABLE `AS_ELEVATOR_NOTICE` ADD COLUMN `ORDER_DETAIL_ID`  bigint(20) DEFAULT NULL COMMENT '订单细节id' ;
ALTER TABLE `AS_ELEVATOR_NOTICE` ADD COLUMN `DATA`  VARCHAR(400) DEFAULT NULL COMMENT '详细数据' ;
