-- ----------------------------
-- Jelynn 2018/3/14 添加
-- ----------------------------
ALTER TABLE `ROBOT_MAPZIP_XREF` DROP COLUMN `LAST_MAP_ZIP_ID`;
ALTER TABLE `ROBOT_MAPZIP_XREF` DROP COLUMN `NEW_MAP_ZIP_ID`;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `MAP_ZIP_ID`  bigint(20) DEFAULT NULL COMMENT '地图压缩包ID' ;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `SCENE_ID`  bigint(20) DEFAULT NULL COMMENT '场景ID';
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `UPDATE_TIME`  datetime DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `DELETE_FLAG`  INT DEFAULT NULL COMMENT '删除标志位 0 :正常 1：删除' ;
ALTER TABLE `ROBOT_MAPZIP_XREF` ADD COLUMN `DELETE_TIME`  datetime DEFAULT NULL COMMENT '删除时间';

-- 修改手术室下单系统中的名称的长度
ALTER TABLE `ERP_APPLIANCE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_APPLIANCE_DEPARTMENT_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_APPLIANCE_PACKAGE_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_OPERATION_DEPARTMENT_TYPE` modify  NAME VARCHAR(200) ;
ALTER TABLE `ERP_OPERATION_TYPE` modify  NAME VARCHAR(200) ;